### ISSUE TITLE
点击star以后反复弹出

### ISSUE THREAD

**Issue by universtar001** [xx025/YanX#10]
开了全局梯子也是，输入了那一串数字 githubID了，一直弹出让star

**Comment by universtar001** [comment]
并且已经star了

**Comment by xx025** [comment]
我用了这个github的api“https://api.github.com/users/universtar001/starred?per_page=1”； 不需要代理，用代理反而可能连不上；
我在我本机测试，现在没问题
![image](https://user-images.githubusercontent.com/71559822/207767425-86a4ffff-b1b3-413b-a43a-c9ec1f2e14eb.png)

**Comment by vercen** [comment]
star还是有问题

**Comment by xx025** [comment]
> star还是有问题

已发现问题原因，稍后会推送新版本进行解决
