### ISSUE TITLE
关于专业目录内有重复行的问题

### ISSUE THREAD

**Issue by Ling2047** [xx025/YanX#12]
作者大大你好！我是酷安用户“墨岭”，在你的文章下提出下载的专业目录文档内有很多行重复，我的设置如下：
![专业选项](https://user-images.githubusercontent.com/122582566/212537434-46f53e8e-db6d-40ae-bd40-3b3a2ef964ab.png)
得到的结果中有重复行，比如：
![专业重复行](https://user-images.githubusercontent.com/122582566/212537504-d6b4f869-8f15-4698-a0d0-5683e59fdcdc.png)
不知道是不是bug呢

**Comment by xx025** [comment]
数据没错，只是之前没加上研究方向这一列数据（之前我没注意，关注的专业有点局限，还真是个问题）

在最新版本我已经加上这一列数据了

最新版本：(v3.1.15)https://github.com/xx025/YanX/releases/latest

如下
![image](https://user-images.githubusercontent.com/71559822/212541832-9b1f47c6-2bb0-4fc4-b850-da0bf0a49dab.png)

**Comment by Ling2047** [comment]
OK，感谢作者大大！
