### ISSUE TITLE
文档无法导出

### ISSUE THREAD

**Issue by SongVXi** [xx025/YanX#13]
![image](https://user-images.githubusercontent.com/116706622/215237404-9c98691c-7df1-44a9-920e-248e3be4532c.png)
没次点击导出之后就没有反应了，虽然左下角会显示开始导出，但是过了一晚了，还是没有导出成功

**Comment by xx025** [comment]
条目多了导出会有一点慢，暂时不知道是什么问题，卸载老版本安装最新版本试试
https://github.com/xx025/YanX/releases/latest

**Comment by SongVXi** [comment]
![image](https://user-images.githubusercontent.com/116706622/215277432-3f719cb8-7b48-4343-894e-870c782791f5.png)
感谢大大，已经可以用了（哪怕是很多条目）但是会有下载限制次数
限制下载次数是每个账号限制三次还是一天限制三次，有没有办法可以解除

**Comment by xx025** [comment]
> ![image](https://user-images.githubusercontent.com/116706622/215277432-3f719cb8-7b48-4343-894e-870c782791f5.png) 感谢大大，已经可以用了（哪怕是很多条目）但是会有下载限制次数 限制下载次数是每个账号限制三次还是一天限制三次，有没有办法可以解除

https://github.com/xx025/YanX/issues/11
