### ISSUE TITLE
你好作者我下了exe程序打不开,没有相应

### ISSUE THREAD

**Issue by GEM123668** [xx025/YanX#18]
exe打不开

**Comment by xx025** [comment]
本人已测试（2023年3月6日15:03），公告部分api连通性有问题，但不妨碍使用

**Comment by GEM123668** [comment]
> 关闭代理
> 
> 确保[https://api.github.com/users/[you](https://api.github.com/users/%5Byou) github name]/starred 能打开
> 
> 确保：研招网能正常访问

你好作者确保那部分没有看明白,能不能解释一下
