### ISSUE TITLE
作者你好，我这输入ID没有反应

### ISSUE THREAD

**Issue by lyfqaz666** [xx025/yanx#19]

**Comment by xx025** [comment]
暂时挂了！，稍等一下吧
如果着急，可直接[联系我](http://xx025.github.io/pages/z9c3c4/)

**Comment by lyfqaz666** [comment]
那我等等吧，麻烦了

**Comment by xx025** [comment]
> 那我等等吧，麻烦了

https://github.com/xx025/yanx/releases/latest
