### ISSUE TITLE
为什么我下载不了？

### ISSUE THREAD

**Issue by 2686157019** [xx025/yanx#21]
![image](https://user-images.githubusercontent.com/78891052/226389990-5370b56c-6d4a-4fa8-ab22-f234c93bc60a.png)

**Comment by xx025** [comment]
是网络问题吗？我明天测试一下吧，暂时不清楚原因，看样子是连不上研招网，也没显示重试

**Comment by xx025** [comment]
> ![image](https://user-images.githubusercontent.com/78891052/226389990-5370b56c-6d4a-4fa8-ab22-f234c93bc60a.png)

出bug了，研招网那边更新了

**Comment by xx025** [comment]
欢迎有能力者提交pr 

简单指出两个模块：
软件每次打开重新下载院校库，已测试现在卡在院校库，后续未知
院校库下载： https://github.com/xx025/yanx/tree/main/utils/uns
专业目录下载： https://github.com/xx025/yanx/tree/main/utils/yzw_dl

**Comment by luciencode** [comment]
不错的软件，望作者有时间修复谢谢啦

**Comment by JiZhiLieShou** [comment]
求作者大大修复，谢谢啦

**Comment by xx025** [comment]
当前我 提供了下载任务的核心代码 在 yzw-dl 分支 ，它支持以python 包的方式安装 进行扩展开发
