### ISSUE TITLE
no release

### ISSUE THREAD

**Issue by universtar001** [xx025/yanx#24]

**Comment by xx025** [comment]
可以 尝试 CLI 程序 输出 JSON , https://github.com/xx025/yanx/tree/yzw-dl

如 https://github.com/xx025/yanx/blob/yzw-dl/dl-data.json

**Comment by universtar001** [comment]
Config Values: {'abloc': '', 'csv_file': 'dl-data.csv', 'csv_title': ['id', '招生单位', '所在地', '院系所', '专业', '学习方式', '研究方向', '拟招人数', '政治', '外语', '业务课一', '业务课二', '考试方式', '指导老师', '备注'], 'dwmc': '', 'json_file': 'dl-data.json', 'mldm': '12', 'output_csvfile': False, 'output_jsonfile': False, 'ssdm': '', 'xxfs': '', 'yjxkdm': '1201', 'zymc': ''}
下载院校信息:  81% 25/31 [00:41<00:09,  1.66s/item]
Traceback (most recent call last):
  File "/content/yzw-dl/main.py", line 90, in <module>
    main()
  File "/content/yzw-dl/main.py", line 59, in main
    for sch in dl_zsyx(**param):
  File "/content/yzw-dl/yzw_dl/dl_zsyx.py", line 68, in dl_zsyx
    return table_dl(_dl_zsyx_one, **kwargs)
  File "/content/yzw-dl/yzw_dl/yzw_default.py", line 40, in table_dl
    one_page_result, text_soup = one_page_dl(**kwargs)
  File "/content/yzw-dl/yzw_dl/dl_zsyx.py", line 39, in _dl_zsyx_one
    招生单位=tds[0].select_one('form a').text,
AttributeError: 'NoneType' object has no attribute 'text'
更改参数后，会出现这些错误，使用示例参数，可以正常运行
已经尝试重新创建虚拟环境，确定配置没问题
python main.py --mldm '12' --yjxkdm '1201'

**Comment by universtar001** [comment]
出错仅限于除专业学位以外的门类

**Comment by universtar001** [comment]
修改config.py后，参数output_jsonfile仍为False

**Comment by universtar001** [comment]
修改config.py后，参数output_jsonfile仍为False

**Comment by universtar001** [comment]
!python main.py --mldm '12' --yjxkdm '1201'  --ssdm 11,这种情况就不会出错

**Comment by universtar001** [comment]
tool.py中第28行 键错了
