### ISSUE TITLE
功能添加

### ISSUE THREAD

**Issue by SONGVXI** [xx025/YanX#33]
请问一下,能不能添加一个功能,就是根据专业课来选择院校

**Comment by SONGVXI** [comment]
准确来说是根据所考的专业课提供专业,然后给出两年的分数线

**Comment by xx025** [comment]
软件不再维护，未来会考虑开发相关的服务系统

**Comment by xx025** [comment]
> 请问一下,能不能添加一个功能,就是根据专业课来选择院校

这是一个很大的工程量，而且研招网本身没有这份数据
