### ISSUE TITLE
【BUG】正常爬取以后无法导出

### ISSUE THREAD

**Issue by LiuYiLin-CA** [xx025/YanX#8]
正常爬取数据以后点击导出按钮，无反应，桌面也无文件

<img width="424" alt="7z_YanX_Win64_2022 9 10" src="https://user-images.githubusercontent.com/54106368/189521314-0ac8d65a-7480-4a16-b1ce-927b9b88bc45.png">

**Comment by xx025** [comment]
请移步：https://github.com/xx025/YanX-Docs/find/main 下载
